# Generated by Django 4.2 on 2023-04-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="protocol_relation", name="id",),
        migrations.AlterField(
            model_name="protocol_relation",
            name="caller_id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
