# Generated by Django 4.2 on 2023-04-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0002_remove_protocol_relation_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol_relation",
            name="middleware_key",
            field=models.CharField(
                default="defaultkeylog145", max_length=100, unique=True
            ),
            preserve_default=False,
        ),
    ]
