# Generated by Django 4.2 on 2023-04-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0003_protocol_relation_middleware_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocol_relation",
            name="caller_url",
            field=models.CharField(max_length=200),
        ),
    ]
