# Generated by Django 4.2 on 2023-04-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Clients", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientdata", old_name="client", new_name="client_id",
        ),
    ]
