# Generated by Django 4.2 on 2023-04-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Protocol_Relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caller_id", models.IntegerField()),
                ("protocol", models.CharField(max_length=7)),
                ("caller_url", models.URLField()),
            ],
        ),
    ]
