# Generated by Django 4.2 on 2023-04-30 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "client_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClientData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Clients.clients",
                    ),
                ),
            ],
        ),
    ]
