# Generated by Django 4.2 on 2023-04-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie_Model",
            fields=[
                ("title", models.CharField(max_length=255)),
                ("release_date", models.DateField()),
                ("description", models.TextField()),
                ("director", models.CharField(max_length=255)),
                ("actors", models.TextField()),
                ("genre", models.CharField(max_length=255)),
                ("rating", models.CharField(max_length=10)),
                ("runtime", models.IntegerField()),
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
