# Generated by Django 4.2 on 2023-04-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book_Model",
            fields=[
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                (
                    "isbn",
                    models.CharField(max_length=13, primary_key=True, serialize=False),
                ),
                ("publisher", models.CharField(max_length=255)),
                ("publication_date", models.DateField()),
                ("description", models.TextField()),
                ("language", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, max_digits=3, null=True),
                ),
            ],
        ),
    ]
